# Generated by Django 3.2.11 on 2022-04-03 15:17

import bookshelf.utilities
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Book', max_length=10, verbose_name='Title')),
                ('subtitle', models.CharField(default='Name', max_length=15, verbose_name='Subtitle')),
                ('desc_title', models.CharField(blank=True, max_length=10, null=True, verbose_name='Title description')),
                ('desc_subtitle', models.CharField(blank=True, max_length=15, null=True, verbose_name='Subtitle description')),
                ('desc_text', models.TextField(default='Lorem ispum description', max_length=300, verbose_name='Description')),
                ('cover_img', models.ImageField(blank=True, null=True, upload_to=bookshelf.utilities.get_timestamp_path, verbose_name='Image on book cover')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='BookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=bookshelf.utilities.get_timestamp_path, verbose_name='Page image')),
            ],
        ),
        migrations.CreateModel(
            name='BookProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_status', models.BooleanField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.book')),
                ('book_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.bookpage')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.book')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bool_null', models.BooleanField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_time', models.DateTimeField(auto_now=True)),
                ('book_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.bookpage')),
                ('inventory_items', models.ManyToManyField(blank=True, to='bookshelf.Item')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.bookprogress')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressConditionStatusItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(default='description', max_length=60, verbose_name='description')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.item')),
                ('page_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookshelf.bookpage')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='#noname', max_length=15)),
                ('win_status', models.BooleanField(blank=True, null=True)),
                ('final_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookshelf.bookpage')),
                ('status_items', models.ManyToManyField(to='bookshelf.ProgressConditionStatusItem')),
            ],
        ),
        migrations.CreateModel(
            name='PageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_path', models.CharField(blank=True, max_length=50, null=True)),
                ('from_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.bookpage')),
                ('key_items', models.ManyToManyField(blank=True, to='bookshelf.Item')),
                ('to_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_page', to='bookshelf.bookpage')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=10)),
                ('text', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pinned', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.book')),
                ('book_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookshelf.bookpage')),
            ],
        ),
        migrations.CreateModel(
            name='DroppedItemSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.bookpage')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.item')),
                ('progress_save', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.progresssave')),
            ],
        ),
        migrations.CreateModel(
            name='DroppedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.bookpage')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.item')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.bookprogress')),
            ],
        ),
        migrations.AddField(
            model_name='bookprogress',
            name='inventory_items',
            field=models.ManyToManyField(blank=True, to='bookshelf.Item'),
        ),
    ]
