# Generated by Django 3.2.11 on 2022-03-20 11:55

import bookshelf.utilities
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Book', max_length=10, verbose_name='Title')),
                ('subtitle', models.CharField(default='Name', max_length=15, verbose_name='Subtitle')),
                ('desc_title', models.CharField(blank=True, max_length=10, null=True, verbose_name='Title description')),
                ('desc_subtitle', models.CharField(blank=True, max_length=15, null=True, verbose_name='Subtitle description')),
                ('desc_text', models.TextField(default='Lorem ispum description', max_length=300, verbose_name='Description')),
                ('cover_img', models.ImageField(blank=True, upload_to=bookshelf.utilities.get_timestamp_path, verbose_name='Image on book cover')),
            ],
        ),
        migrations.CreateModel(
            name='BookStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.book')),
            ],
        ),
        migrations.CreateModel(
            name='BookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('text', models.TextField()),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.bookstage')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='first_stage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_page', to='bookshelf.bookstage', verbose_name='Start page'),
        ),
    ]
