# Generated by Django 3.2.11 on 2022-04-03 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookshelf', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookpage',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.book'),
        ),
        migrations.AddField(
            model_name='bookpage',
            name='page_items',
            field=models.ManyToManyField(blank=True, to='bookshelf.Item'),
        ),
        migrations.AddField(
            model_name='book',
            name='first_page',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_page', to='bookshelf.bookpage', verbose_name='Start stage'),
        ),
        migrations.AddField(
            model_name='book',
            name='progress_conditions',
            field=models.ManyToManyField(blank=True, to='bookshelf.ProgressCondition', verbose_name='lose/win conditions'),
        ),
        migrations.AlterUniqueTogether(
            name='pagelink',
            unique_together={('from_page', 'to_page')},
        ),
        migrations.AlterUniqueTogether(
            name='bookprogress',
            unique_together={('user', 'book')},
        ),
    ]
