# Generated by Django 3.2.11 on 2022-04-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='inventory_limit',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='bookprogress',
            name='inventory_full',
            field=models.BooleanField(default=False),
        ),
    ]
