# Generated by Django 3.2.11 on 2022-04-03 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_auto_20220403_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookprogress',
            name='inventory_full',
        ),
    ]
