# Generated by Django 3.2.11 on 2022-04-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0005_alter_note_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='progresscondition',
            name='name',
            field=models.CharField(default='#noname', max_length=25),
        ),
        migrations.AlterField(
            model_name='progresscondition',
            name='win_status',
            field=models.BooleanField(default=True),
        ),
    ]
