# Generated by Django 3.2.11 on 2022-03-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0005_alter_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpage',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
