# Generated by Django 3.2.11 on 2022-03-22 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0009_auto_20220322_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookprogress',
            name='final_text',
        ),
        migrations.RemoveField(
            model_name='progresscondition',
            name='final_text',
        ),
        migrations.AddField(
            model_name='progresscondition',
            name='win_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookshelf.bookpage'),
        ),
        migrations.DeleteModel(
            name='FinalText',
        ),
    ]
