# Generated by Django 3.2.11 on 2022-03-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='name',
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.TextField(default='noteName', max_length=30),
            preserve_default=False,
        ),
    ]
