# Generated by Django 3.2.11 on 2022-03-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0007_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookprogress',
            name='win_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
