# Generated by Django 3.2.11 on 2022-03-22 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0008_bookprogress_win_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='text', max_length=30)),
                ('text', models.TextField(default='text')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressConditionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(default='description', max_length=60, verbose_name='description')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.item')),
                ('page_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookshelf.bookpage')),
            ],
        ),
        migrations.RemoveField(
            model_name='wincondition',
            name='book',
        ),
        migrations.RemoveField(
            model_name='wincondition',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='wincondition',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='progresscondition',
            name='condition_item',
        ),
        migrations.RemoveField(
            model_name='progresscondition',
            name='condition_item_location',
        ),
        migrations.AddField(
            model_name='book',
            name='progress_conditions',
            field=models.ManyToManyField(blank=True, to='bookshelf.ProgressCondition', verbose_name='lose/win conditions'),
        ),
        migrations.DeleteModel(
            name='LoseCondition',
        ),
        migrations.DeleteModel(
            name='WinCondition',
        ),
        migrations.AddField(
            model_name='bookprogress',
            name='final_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookshelf.finaltext'),
        ),
        migrations.AddField(
            model_name='progresscondition',
            name='final_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookshelf.finaltext'),
        ),
        migrations.AddField(
            model_name='progresscondition',
            name='items',
            field=models.ManyToManyField(to='bookshelf.ProgressConditionItem'),
        ),
    ]
