# Generated by Django 3.2.11 on 2022-03-22 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0012_rename_win_page_progresscondition_final_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressconditionstatusitem',
            name='page_position',
            field=models.ForeignKey(blank=True, default='inventory', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookshelf.bookpage'),
        ),
    ]
