# Generated by Django 3.2.11 on 2022-03-23 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0013_alter_progressconditionstatusitem_page_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresscondition',
            name='name',
            field=models.CharField(default='#noname', max_length=15),
        ),
        migrations.AlterField(
            model_name='progressconditionstatusitem',
            name='page_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookshelf.bookpage'),
        ),
    ]
