# Generated by Django 3.2.11 on 2022-04-19 15:35

import about_me.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0002_alter_portfolioskillcard_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioskillcard',
            name='cover_img',
            field=models.FileField(upload_to=about_me.utilities.get_timestamp_path, verbose_name='tech icon '),
        ),
    ]
