# Generated by Django 3.2.11 on 2022-04-19 16:11

import about_me.utilities
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0003_alter_portfolioskillcard_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioprojectcard',
            name='logo_img',
            field=models.FileField(default=django.utils.timezone.now, upload_to=about_me.utilities.get_timestamp_path, verbose_name='Project logo img'),
            preserve_default=False,
        ),
    ]
