# Generated by Django 3.2.11 on 2022-04-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0004_alter_portfolioprojectcard_logo_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioprojectcard',
            name='git_link',
        ),
    ]
