# Generated by Django 3.2.11 on 2022-04-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0005_remove_portfolioprojectcard_git_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioskillcard',
            name='border_color',
        ),
        migrations.AddField(
            model_name='portfolioprojectcard',
            name='name',
            field=models.CharField(default='noname', max_length=15),
            preserve_default=False,
        ),
    ]
