# Generated by Django 3.2.11 on 2022-04-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0006_auto_20220420_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioprojectcard',
            name='sort_index',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='portfolioskillcard',
            name='sort_index',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='portfolioprojectcard',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolioskillcard',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
