# Generated by Django 3.2.11 on 2022-05-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0007_auto_20220420_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioprojectcard',
            name='slowly_redirect',
            field=models.BooleanField(default=False),
        ),
    ]
