# Generated by Django 3.2.11 on 2022-01-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book0', '0003_pagelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagelink',
            name='name',
            field=models.TextField(default='???'),
            preserve_default=False,
        ),
    ]
