# Generated by Django 3.2.11 on 2022-02-02 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book0', '0005_auto_20220118_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagelink',
            name='from_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book0.bookpage'),
        ),
        migrations.AlterField(
            model_name='pagelink',
            name='to_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_page', to='book0.bookpage'),
        ),
    ]
