# Generated by Django 3.2.11 on 2022-02-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book0', '0006_auto_20220202_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_img',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
