# Generated by Django 3.2.11 on 2022-02-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book0', '0008_alter_book_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_img',
            field=models.ImageField(null=True, upload_to='static/uploads/book_cover'),
        ),
    ]
