# Generated by Django 3.2.11 on 2022-02-04 14:05

import book0.utilities
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book0', '0009_alter_book_cover_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_img',
            field=models.ImageField(null=True, upload_to=book0.utilities.get_timestamp_path, verbose_name='Изборажение'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.TextField(unique=True, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=book0.utilities.get_timestamp_path, verbose_name='Обложка')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book0.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Доп иллюстрация',
                'verbose_name_plural': 'Доп иллюстрации',
            },
        ),
    ]
