# Generated by Django 3.2.11 on 2022-02-04 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book0', '0010_auto_20220204_1405'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdditionalImage',
            new_name='BookAdditionalImage',
        ),
    ]
