# Generated by Django 3.2.11 on 2022-02-04 17:37

import book0.utilities
from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('book0', '0012_additionalimage_bb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalimage',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=book0.utilities.get_timestamp_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=book0.utilities.get_timestamp_path, verbose_name='Изображение'),
        ),
    ]
