# Generated by Django 3.2.11 on 2022-02-04 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book0', '0013_auto_20220204_1737'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalImage',
        ),
        migrations.DeleteModel(
            name='Bb',
        ),
    ]
