# Generated by Django 3.2.11 on 2022-02-04 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book0', '0014_auto_20220204_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookadditionalimage',
            old_name='image',
            new_name='cover_img',
        ),
    ]
