# Generated by Django 3.2.11 on 2022-02-05 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book0', '0015_rename_image_bookadditionalimage_cover_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='first_page',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_page', to='book0.bookpage'),
        ),
    ]
