# Generated by Django 3.2.11 on 2022-02-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book0', '0017_bookprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='bookprogress',
            name='items',
            field=models.ManyToManyField(to='book0.Item'),
        ),
    ]
