# Generated by Django 3.2.11 on 2022-02-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book0', '0018_auto_20220206_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpage',
            name='items',
            field=models.ManyToManyField(to='book0.Item'),
        ),
    ]
