# Generated by Django 3.2.11 on 2022-02-09 14:38

import book0.utilities
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book0', '0019_bookpage_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to=book0.utilities.get_timestamp_path, verbose_name='Изборажение'),
        ),
        migrations.AlterField(
            model_name='book',
            name='first_page',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_page', to='book0.bookpage'),
        ),
        migrations.AlterField(
            model_name='bookpage',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='book0.Item'),
        ),
    ]
