# Generated by Django 3.2.11 on 2022-02-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book0', '0022_alter_bookpage_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpage',
            name='items',
            field=models.ManyToManyField(to='book0.Item'),
        ),
    ]
