# Generated by Django 3.2.11 on 2022-02-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book0', '0023_alter_bookpage_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagelink',
            name='items',
            field=models.ManyToManyField(to='book0.Item'),
        ),
        migrations.AlterField(
            model_name='bookpage',
            name='items',
            field=models.ManyToManyField(blank=True, to='book0.Item'),
        ),
        migrations.AlterField(
            model_name='bookprogress',
            name='items',
            field=models.ManyToManyField(blank=True, to='book0.Item'),
        ),
    ]
