# Generated by Django 3.2.11 on 2022-02-15 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book0', '0024_auto_20220210_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpage',
            name='title',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='pagelink',
            name='items',
            field=models.ManyToManyField(blank=True, to='book0.Item'),
        ),
        migrations.CreateModel(
            name='ProgressSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book0.bookpage')),
                ('items', models.ManyToManyField(blank=True, to='book0.Item')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book0.bookprogress')),
            ],
        ),
    ]
