# Generated by Django 3.2.11 on 2022-02-18 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book0', '0025_auto_20220215_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroppedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book0.bookpage')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book0.item')),
            ],
        ),
        migrations.AddField(
            model_name='bookprogress',
            name='dropped_item',
            field=models.ManyToManyField(blank=True, to='book0.DroppedItem'),
        ),
    ]
