# Generated by Django 3.2.11 on 2022-02-19 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book0', '0028_delete_droppeditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroppedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book0.bookpage')),
                ('book_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book0.bookprogress')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book0.item')),
            ],
        ),
    ]
