# Generated by Django 3.2.11 on 2022-02-19 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book0', '0030_droppeditemsave'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DroppedItemSave',
        ),
    ]
