# Generated by Django 3.2.11 on 2022-02-19 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book0', '0031_delete_droppeditemsave'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroppedItemSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book0.bookpage')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book0.item')),
                ('progress_save', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book0.progresssave')),
            ],
        ),
    ]
