# Generated by Django 3.2.11 on 2022-02-20 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book0', '0033_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
