# Generated by Django 3.2.11 on 2022-02-20 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book0', '0034_delete_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book0.bookpage')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book0.bookprogress')),
            ],
        ),
    ]
