# Generated by Django 3.2.11 on 2022-03-15 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0003_alter_advuser_send_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testmodel',
            new_name='Note',
        ),
    ]
