# Generated by Django 3.2.11 on 2022-02-24 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.item')),
                ('condition_item_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.bookpage')),
            ],
        ),
        migrations.CreateModel(
            name='WinCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.progresscondition')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.bookprogress')),
            ],
        ),
        migrations.CreateModel(
            name='LoseCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.progresscondition')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.bookprogress')),
            ],
        ),
    ]
