# Generated by Django 3.2.11 on 2022-02-07 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_first_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagelink',
            name='from_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.bookpage'),
        ),
        migrations.AlterField(
            model_name='pagelink',
            name='to_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_page', to='book.bookpage'),
        ),
    ]
