# Generated by Django 3.2.11 on 2022-02-08 10:56

import book.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20220207_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_img',
            field=models.ImageField(blank=True, upload_to=book.utilities.get_timestamp_path, verbose_name='Обложка книги'),
        ),
        migrations.AddField(
            model_name='pagelink',
            name='name_path',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='pagelink',
            unique_together={('from_page', 'to_page')},
        ),
    ]
