# Generated by Django 3.2.11 on 2022-02-09 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_rename_items_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookprogress',
            old_name='page',
            new_name='book_page',
        ),
    ]
