# Generated by Django 3.2.11 on 2022-02-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_rename_page_bookprogress_book_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookprogress',
            name='key_items',
            field=models.ManyToManyField(to='book.Item'),
        ),
    ]
