# Generated by Django 3.2.11 on 2022-02-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_bookprogress_key_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookpage',
            old_name='item',
            new_name='page_items',
        ),
        migrations.RenameField(
            model_name='bookprogress',
            old_name='key_items',
            new_name='inventory_items',
        ),
        migrations.AddField(
            model_name='pagelink',
            name='key_items',
            field=models.ManyToManyField(to='book.Item'),
        ),
    ]
