# Generated by Django 3.2.11 on 2022-02-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20220211_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookprogress',
            name='inventory_items',
            field=models.ManyToManyField(blank=True, to='book.Item'),
        ),
        migrations.AlterField(
            model_name='pagelink',
            name='key_items',
            field=models.ManyToManyField(blank=True, to='book.Item'),
        ),
    ]
