# Generated by Django 3.2.11 on 2022-02-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20220211_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookpage',
            name='page_items',
        ),
        migrations.AddField(
            model_name='bookpage',
            name='page_items',
            field=models.ManyToManyField(blank=True, to='book.Item'),
        ),
    ]
