# Generated by Django 3.2.11 on 2022-02-17 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20220211_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_time', models.TimeField(auto_now=True)),
                ('book_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.bookpage')),
                ('inventory', models.ManyToManyField(blank=True, to='book.Item')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.bookprogress')),
            ],
        ),
    ]
