# Generated by Django 3.2.11 on 2022-02-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_progresssave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresssave',
            name='save_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
