# Generated by Django 3.2.11 on 2022-02-22 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_droppeditemsave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progresssave',
            old_name='inventory',
            new_name='inventory_items',
        ),
    ]
