# Generated by Django 3.2.11 on 2022-02-22 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_rename_inventory_progresssave_inventory_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droppeditem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.item'),
        ),
    ]
