# Generated by Django 3.2.11 on 2022-02-22 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_alter_droppeditem_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='droppeditemsave',
            old_name='save',
            new_name='progress_save',
        ),
    ]
