# Generated by Django 3.2.11 on 2022-02-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_alter_note_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
