# Generated by Django 3.2.11 on 2022-02-23 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0021_note_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='book_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.bookpage'),
        ),
    ]
