# Generated by Django 3.2.11 on 2022-03-20 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookpage',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='bookstage',
            name='book',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookPage',
        ),
        migrations.DeleteModel(
            name='BookStage',
        ),
    ]
