# Generated by Django 3.2.11 on 2022-03-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0006_alter_bookpage_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bool_null', models.BooleanField(blank=True, default=None, null=True)),
            ],
        ),
    ]
