# Generated by Django 3.2.11 on 2022-03-22 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0011_auto_20220322_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progresscondition',
            old_name='win_page',
            new_name='final_page',
        ),
    ]
