# Generated by Django 3.2.11 on 2022-03-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0014_auto_20220323_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresscondition',
            name='win_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
